---
- hosts: dev
  remote_user: root
  tasks:
    
    # User management

    - name: Install sudo
      package:
        name: sudo
        state: present

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create/add musicallyut to wheel group
      user: 
        name: musicallyut 
        groups: wheel 
        append: yes 
        state: present 
        createhome: yes

    - name: Set up authorized keys for the musicallyut user
      authorized_key: 
        user: musicallyut 
        key: "{{item}}"
      with_file:
        - keys/id_ed25519.pub

    # Install dev tools

    - name: Install VIM
      package:
        name: vim
        state: present

    - name: Install vim-plug
      get_url: 
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/musicallyut/.vim/autoload/plug.vim
        owner: musicallyut

    - name: Install git
      package:
        name: git
        state: present

    - name: Install tmux
      package:
        name: tmux
        state: present

    - name: Install htop
      package:
        name: htop
        state: present

    - name: Ensures local/z dir exists
      file: 
        path: /home/musicallyut/.local/z 
        state: directory
        owner: musicallyut

    - name: Install z.sh
      get_url: 
        url: https://raw.githubusercontent.com/rupa/z/master/z.sh
        dest: /home/musicallyut/.local/z/z.sh
        owner: musicallyut

    - name: Install nvm.sh
      become: true
      become_user: musicallyut
      warn: false
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    # Copy configuration files

    - name: Copy vimrc
      copy:
        src: dotfiles/vimrc
        dest: /home/musicallyut/.vimrc
        owner: musicallyut

    - name: Copy bashrc
      copy:
        src: dotfiles/bashrc
        dest: /home/musicallyut/.bashrc
        owner: musicallyut

    - name: Copy tmux.conf
      copy:
        src: dotfiles/tmux.conf
        dest: /home/musicallyut/.tmux.conf
        owner: musicallyut

    - name: Copy gitconfig
      copy:
        src: dotfiles/gitconfig
        dest: /home/musicallyut/.gitconfig
        owner: musicallyut

    - name: Copy gitignore
      copy:
        src: dotfiles/gitignore
        dest: /home/musicallyut/.gitignore
        owner: musicallyut
